### ISSUE TITLE
Передача параметра ударения

### ISSUE THREAD

**Issue by lavrenkov-sketch** [Aculeasis/rhvoice-proxy#3]
Здраствуйте как передать пареметр ударения например +, где находиться конфиг по умолчанию?
редктирование стандарных настроек не помогает

**Comment by Aculeasis** [comment]
`git clone https://github.com/Aculeasis/rhvoice-proxy && cd rhvoice-proxy && python3 setup.py install`

По умолчанию используется `/usr/local/etc/RHVoice/RHVoice.conf`.  `stress_marker=]` работает, можно и + если без [препроцессора](https://github.com/vantu5z/RHVoice-dictionary/tree/master/tools/preprocessing) иначе он его в 'плюс' конвертирует.
