### ISSUE TITLE
RHVoice 1.8.0 supporting

### ISSUE THREAD

**Issue by yellow-sky** [Aculeasis/rhvoice-proxy#6]
Now output:
Warning! Unsupported library version, use API 1.2.0. Supported: ('0.7.2', '1.0.0', '1.2.0', '1.2.1', '1.2.2', '1.2.3', '1.4.2'), library: 1.8.0.
    raise RuntimeError('RHVoice: engine initialization error')
RuntimeError: RHVoice: engine initialization error

**Comment by Aculeasis** [comment]
What OS and python version did you use? How did you run it?
I tested 1.8 and 1.12 (from master) with python 3.7 on ubuntu 20, and it works.

I think one of the init params is wrong. It's probably data_path, config_path or resources.

**Comment by yellow-sky** [comment]
Yes, after configure data_path and config_path it's work!
